### ISSUE TITLE
www.celeryproject.org needs updating

### ISSUE THREAD

**Issue by jakubczaplicki** [celery/celeryproject#13]
http://www.celeryproject.org/ might be a bit misleading. The latest news shouts that "Celery 3.1 Is Now Available!", yet the current stable version is 4.0.1. Perhaps it would be worth adding a news about 4.0 ?

**Comment by fireantology** [comment]
Hi,
News are managed manually normally by asksol but thanks to your comment I just added the news. However in the homepage you do have the button the right that queries pypi directly and shows the latest version. We should also generate the news automatically :-)

**Comment by jezdez** [comment]
@fireantology So correct me if I'm wrong, but the site states that "Celery 4.1 is now available", while there is no such release. Could you please update the news to note with the correct version? Cheers!

**Comment by fireantology** [comment]
Right. I will

**Comment by jezdez** [comment]
@fireantology Hey there, seems like you updated the version incorrectly. The latest version is 4.0.2, *not* 4.2. Sorry for being a pain, but this has caused confusion over here and I'm just trying to prevent people searching for a non-existing version.

**Comment by fireantology** [comment]
Houch, I was also quite confused, I did it in a rush. Should be fine now.
Thanks

**Comment by jezdez** [comment]
@fireantology Thank you! 🍰 🎁 ❤️
