### ISSUE TITLE
Celery Project site New Hosting service

### ISSUE THREAD

**Issue by auvipy** [celery/celeryproject#16]

**Comment by auvipy** [comment]
@thedrow @ask @fireantology

**Comment by georgepsarakis** [comment]
@auvipy what does this issue concern?

**Comment by thedrow** [comment]
Why do we need a new hosting service?

**Comment by fireantology** [comment]
Yes we do. Rackspace is ending open source support for free and my credit card is configured on the account. We need to find new hosting by end of December. Shall we try to tweet to Dogital Ocean ?

**Comment by thedrow** [comment]
Sure!
Alternatively we could convert this site to a static site and host it on Github.

**Comment by thedrow** [comment]
I just twitted them https://twitter.com/the_drow/status/930369386946408448

**Comment by PMickael** [comment]
I can provide hosting service for Free, A little vm for example.

**Comment by thedrow** [comment]
@PMickael Where would you host the website?

**Comment by PMickael** [comment]
All my servers are provide by online.net, I do managed web hosting for french companies.

**Comment by georgepsarakis** [comment]
@thedrow I think the Github option is probably the best.

**Comment by thedrow** [comment]
But it requires time to convert all the website to Jekyll.
Until we do so, what @PMickael is offering sounds like our best option.

**Comment by georgepsarakis** [comment]
@thedrow how about [Heroku](https://blog.heroku.com/heroku-free-dynos) ?

**Comment by PMickael** [comment]
@georgepsarakis Heroku to do not offer full time online service for Free (or maybe I read it wrong)
It's not like it was a critical website and resource consumer either so anyway you know if there isn't any other solution I'm open to host ^^

**Comment by fireantology** [comment]
Please don't underestimate the loads that a website like celryproject.org generates. Here a screenshot from analytics
![image](https://user-images.githubusercontent.com/511447/32858669-8ac3aa52-ca4c-11e7-8e84-80529e56912c.png)

**Comment by PMickael** [comment]
Here an example of what I'm hosting :)
![image](https://user-images.githubusercontent.com/122271/32859722-999d6a56-ca4f-11e7-9f6f-d8c144e6c530.png)

**Comment by fireantology** [comment]
At least I gave you a chance to show off :-).
For me is all yours, if the guys agree I will export the DB so that you can setup the new site on your servers.
For DNS instead I thinks is still Ask that manages them.

**Comment by thedrow** [comment]
I tried contacting him the other day, no luck.

**Comment by fireantology** [comment]
Website is going down at the end of the month

**Comment by fireantology** [comment]
What I can do is to host it on a server paid by my own company as a sponsor for the project if you all agree but we will still need to have @ask to switch the dns before the end of the year.
Or we can let @PMickael take it, for me is the same.

**Comment by PMickael** [comment]
I just ping him on twitter :)

**Comment by ask** [comment]
Yeah, DNS is on asmallorange. I can update it, but guess need IP address for the A record?

**Comment by fireantology** [comment]
@PMickael So you ser it up or I do ?

**Comment by fireantology** [comment]
@PMickael any news ? What do we do ? If no answer in 2 days I will move on my own server sponsored by my own company.

**Comment by fireantology** [comment]
Got also a sql dump for restore the db.

**Comment by auvipy** [comment]
good job @fireantology let's see

**Comment by fireantology** [comment]
We finally can keep rackspace, they clarified in the support ticket

> We apologize for any confusion communication may have caused. While we’re no longer accepting new applicants to the Open Source Discount (OSS) program, all existing OSS program customers will keep their credits

So the problem does not exist.
Rackaspace will keep the support
