### ISSUE TITLE
DNS issues for celeryproject.org

### ISSUE THREAD

**Issue by jerr0328** [celery/celeryproject#39]
This relates to #24, where the CNAME needed to be changed for docs.celeryproject.org to have SSL working. I'm still seeing that issue, but that's because the second NS record for celeryproject.org is not in sync with the first one. You can see intoDNS's report showing the mismatch SOA serial numbers: https://intodns.com/celeryproject.org

> Looks like your nameservers do not agree on the SOA serial. Ths SOA records as reported by your nameservers: 
67.228.207.194 ->  2019072901
67.19.36.196 ->  2018102500
This can cause some serious problems that is why you should fix this asap.

Please see https://github.com/celery/celeryproject/issues/24#issuecomment-516306207 for more details about the mismatch, but this really is a new issue that should be addressed with your DNS provider, asmallorange.

**Comment by auvipy** [comment]
thanks a lot

**Comment by jerr0328** [comment]
Looks like the nameservers are updated and in agreement now. Thanks!
