### ISSUE TITLE
docs.celeryproject.org and celeryproject.org are down

### ISSUE THREAD

**Issue by colons** [celery/celeryproject#52]

**Comment by coderanger** [comment]
Will report back if I can get in touch with her. I've reached out to the PSF Infra team to see if they would be willing to hold the domain as a trusted party even if you would rather just roll forward to a new one so you aren't blocked for now :)

**Comment by auvipy** [comment]
yeah please, that would be really helpful. I have my email in github

**Comment by mrmonkington** [comment]
@auvipy I am sorry to revisit this point (and also sorry if this is not the best channel), but would you be able to confirm for me that there are no '@celeryproject.org' addresses with maintainer rights for Celery on PyPI? I can still see 'ask' listed on there and the changelog implies that she was using ask@celeryproject.org.

My concerns are that if the Celery maintainers no longer have control of this MX for celeryproject.org then it is not possible to rule out a bad actor impersonating ask@celeryproject.org, using the PyPI password reset, and having write access to the package.

**Comment by ewdurbin** [comment]
The only existing user on PyPI (@ask) with a celeryproject.org address has been deactivated.

No account activity has been noted since the domain was compromised.

**Comment by bryanculver** [comment]
Looks like there may have been a compromise with the account at the hosting company, A Small Orange.

Might be worth contacting them or Enom because I'm sure they wouldn't appreciate takeovers.

NS Records still point to there and nothing in WHOIS has changed since April of last year:

```
# whois.enom.com



Domain Name: celeryproject.org
Registry Domain ID: D156435169-LROR
Registrar WHOIS Server: WHOIS.ENOM.COM
Registrar URL: WWW.ENOM.COM
Updated Date: 2021-05-01T05:08:39.00Z
Creation Date: 2009-06-15T12:30:15.00Z
Registrar Registration Expiration Date: 2022-06-15T19:30:15.00Z
Registrar: ENOM, INC.
Registrar IANA ID: 48
Domain Status: clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited
Registrant Name: REDACTED FOR PRIVACY
...additional registrant information...
Name Server: NS1.ASMALLORANGE.COM
Name Server: NS2.ASMALLORANGE.COM
DNSSEC: unsigned
Registrar Abuse Contact Email: ABUSE@ENOM.COM
Registrar Abuse Contact Phone: +1.4259744689
URL of the ICANN WHOIS Data Problem Reporting System: HTTP://WDPRS.INTERNIC.NET/
>>> Last update of WHOIS database: 2022-03-30T18:30:00.00Z <<<
```

**Comment by ewdurbin** [comment]
Good news, as of a few minutes ago the transfer of this domain has started and will be registered in perpetuity by the Python Software Foundation.

Celery project maintainers can contact infrastructure-staff@python.org to discuss next steps and management of the domain moving forward.

**Comment by ericholscher** [comment]
@ewdurbin Great to hear. We'd love to get the Google results working again, so let me know if you want to re-point `docs.` to `readthedocs.io`, which should automatically redirect all existing docs links.

**Comment by thedrow** [comment]
Thank you everyone for helping to handle this issue. I'm sorry I could not make more time to get involved in fixing it.
The fact that we didn't own the domain really stressed me out but I didn't know what I should do to resolve this.

I've instructed one of my employees to contact the PSF and engage the contributors on the matter.
I'll try to find a time to write a retrospective on this incident.

**Comment by ewdurbin** [comment]
Just an update: still waiting for transfer to complete. Will confirm here and respond to the celery project rep at that time.

**Comment by ewdurbin** [comment]
<img width="654" alt="screenshot showing a notice of successful transfer of celeryproject.org to the PSF" src="https://user-images.githubusercontent.com/1200832/163112859-a3584159-1f0f-4fe4-939a-ec9bd13e8a4d.png">

We're all set!

**Comment by ewdurbin** [comment]
I've moved the DNS NS records to Gandi for now, but that may take some time to propagate.

**Comment by ewdurbin** [comment]
For the time being I have configured apex, www, and docs .celeryproject.org to temporary redirect to docs.celeryq.deva

**Comment by auvipy** [comment]
> For the time being I have configured apex, www, and docs .celeryproject.org to temporary redirect to docs.celeryq.deva

i reached the infra team please check.

**Comment by ewdurbin** [comment]
Apologies! I responded yesterday but mishandled the To: field and didn't include you. You should have an email in your inbox now.
