### ISSUE TITLE
Include parse-url support for rabbitmq (amqp://) scheme

### ISSUE THREAD

**Issue by timotei-za** [celery/celeryproject#60]
**Problem**: Singleton base are not supported if rabbitmq broker are used to assimilate the tasks.
**Error**: `Redis URL must specify one of the following schemes (redis://, rediss://, unix://)`

**Please include rabbitmq (amqp://) parse_url function from connection.py file -> line - approx 1194**

**If there is another way to use singleton with the rabbitmq broker, I would be very grateful to know. Thanks!**

![Image 4](https://user-images.githubusercontent.com/86377196/183218022-0ec42316-af5b-49ef-97d8-d63b0fb4632f.png)

**Comment by auvipy** [comment]
isn't that already supported? what am I missing? or what are you exactly asking for?

**Comment by timotei-za** [comment]
@auvipy the problem is that when I use rabbitmq as a broker, I can't use Singleton property inside of decorator as a base, because parse_url method doesn't support that rabbitmq system

**Comment by timotei-za** [comment]
@auvipy and yes, this is not supported!!
